
const wGalerie = 1000;
const hGalerie = 1084;
const ratioGalerie = wGalerie/hGalerie;

let projectList = [

    // types : 0 = Projet personnel ; 1 = projet d'école ; 2 = projet de stage
    // 0
    // {},
    // A PROPOS
    // {
    //     offset : [250,0],
    //     size : [772,576],
    //     id : "aPropos",
    //     name: "Bienvenue !",
    //     text: "Je m'appelle Eliot, je suis artiste designer diplômé en création industrielle à l'ENSCI - Les Ateliers. Mon approche du design et de la création est à la fois poétique, rêveuse ; et réaliste, consciente des enjeux sociétaux, écologiques et techniques de demain. <br><br>  Pour en savoir plus sur ma <u>pratique</u>, sur les <u>services</u> que je propose ainsi que sur mes <u>travaux</u> actuels et passés, je vous invite à parcourir les différents espaces de ce site. <br><br> Je suis ouvert à toute proposition de travail ou de collaboration ! <br> Bonne visite :)",
    //     desc:"",
    //     type: "",
    //     date: "",
    //     spot : 1,
    //     imgSrc1 : "none",
    //     imgSrc2 : "none",
    //     class : "multimedia mediation illustration objet",
    //     link : "",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // TERRES LOINTAINES
    {
        offset : [3200,230],
        size : [707,208],
        id: "terresLointaines",
        name: "Terres Lointaines",
        text: "Ce court métrage, inspiré du 'Monde d'Edena' écrit et dessiné par Moebius, raconte l'histoire d'un être humanoïde échoué sur une terre inconnue, qu'il va devoir arpenter et découvrir.",
        desc:"",
        type: "Projet d'études",
        date: "2020",
        spot : 1,
        imgSrc1 : "terreslointaines.png",
        scale : 1,
        imgSrc2 : "none",
        class : "illustration multimedia ",
        link : "",
        mirror : 0,
        miniature : 0,
        
    },
    // OLLAS
    // {
    //     offset : [839,396],
    //     size : [288,115],
    //     id: "ollas",
    //     name: "Ollas",
    //     text: "Ollas en terre cuite, dessinée dans le cadre de mon stage chez les Transfarmers.",
    //     desc:"",
    //     type: "Projet de stage",
    //     date: "2021",
    //     spot : 1,
    //     imgSrc1 : "none",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // POL
    // {
    //     offset : [6402,0],
    //     size : [401,294],
    //     id: "pol",
    //     name: "Pol",
    //     text: "Issu d’un partenariat avec la galerie d’art Bertrand Grimont, ce projet est une tentative de contrepied à la tendance actuelle des scénographies jetables.",
    //     desc:"",
    //     type: "Projet d'études",
    //     date: "2019",
    //     spot : 1,
    //     imgSrc1 : "pol.jpg",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "",
    //     mirror : 0,
    //     miniature : 0,

    // },
    // LAMPE ICOSAEDRE
    // {
    //     offset : [4260,725],
    //     size : [302,361],
    //     id: "lampeIcosaedre",
    //     name: "Lampe Icosaèdre",
    //     text: "Fabriquée à partir d'une ancienne maquette de projet. <br>Sa lumière diffuse est idéale pour le travail de bureau !",
    //     desc:"",
    //     type: "Projet personnel",
    //     date: "2018",
    //     spot : 1,
    //     imgSrc1 : "lampe-icosaedre.png",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "none",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // CHAISE ATTACHE
    // {
    //     offset : [4289,0],
    //     size : [245,350],
    //     id: "chaiseAttache",
    //     name: "Chaise Attache",
    //     text: "Cette assise démontable réutilise le principe d'assemblage de Pol.",
    //     desc:"",
    //     type: "Projet personnel",
    //     date: "2020",
    //     spot : 1,
    //     imgSrc1 : "none",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "none",
    //     mirror : 0,
    //     miniature : 1,
        
    // },
    // FABRIQUE A BRAC
    {
        offset : [0,370],
        size : [652,481],
        id: "fabriqueABrac",
        name: "Fabrique À Brac",
        text: "Les objets industriels qui nous entourent possèdent des potentiels d’usage intéressants et souvent inexploités.<br><br>A travers mon projet de deeplôme, j'explore différentes pistes de projet pour inciter les gens à regarder les objets industriels avec curiosité et ingéniosité",
        desc:"",
        type: "Projet de deeplôme",
        date: "2022",
        spot : 1,
        imgSrc1 : "lafabriqueabrac.gif",
        scale : 1,
        imgSrc2 : "none",
        class : "mediation multimedia",
        link : "",
        mirror : 0,
        miniature : 0,
        
    },
    // NASA
    {
        offset : [0,0],
        size : [670,380],
        id: "nasa",
        name: "NASA",
        text: "Ici dans ce porfolio pour porter la fabrique à Brac :^D",
        desc:"",
        type: "",
        date: "2018",
        spot : 1,
        imgSrc1 : "",
        scale : 1,
        imgSrc2 : "none",
        class : "objet ",
        link : "none",
        mirror : 0,
        miniature : 0,
        
    },
    // LAMPE RESSORT
    // {
    //     offset : [6575,288],
    //     size : [234,460],
    //     id: "lampeRessort",
    //     name: "Lampe Ressort",
    //     text: "Ce projet est un objet manifeste, un prototype de lampe d’architecte dont les principes de fonctionnement sont mis en valeur. L’objectif est de rendre l’objet plus compréhensible et tangible pour l’utilisateur.",
    //     desc:"",
    //     type: "Projet personnel",
    //     date: "2018",
    //     spot : 1,
    //     imgSrc1 : "lamperessort.png",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // TABLE BASSE
    // {
    //     offset : [2703,0],
    //     size : [505,155],
    //     id: "tableBasse",
    //     name: "Table Basse",
    //     text: "Fabriquée à partir d'un vieux meuble",
    //     desc:"",
    //     type: "Projet personnel",
    //     date: "2022",
    //     spot : 1,
    //     imgSrc1 : "none",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "none",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // LAMPE COLETTE
    // {
    //     offset : [1450,800],
    //     size : [189,93],
    //     id: "lampeColette",
    //     name: "Lampe Colette",
    //     text: "Cette applique murale orientable est conçue autour de la pince à dessin, objet industriel que j’ai détourné de son utilisation principale pour en faire une pièce d’assemblage à multiples facettes.",
    //     desc:"",
    //     type: "Projet personnel",
    //     date: "2022",
    //     spot : 1,
    //     imgSrc1 : "lampepince.png",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // CHMUP
    {
        offset : [2250,150],
        size : [424,386],
        id: "chmupTheDog",
        name: "Chmup The Dog",
        text: "Chmup, chien fidèle aux pouvoirs télékinésiques, part à la recherche de son maitre fait prisonnier dans un repaire de scientifiques.",
        desc:"",
        type: "Projet personnel",
        date: "2019",
        spot : 1,
        imgSrc1 : "course.gif",
        scale : 0.6,
        imgSrc2 : "none",
        class : "multimedia illustration ",
        link : "",
        mirror : 0,
        miniature : 0,
        
    },
    // VASE
    // {
    //     offset : [2764,145],
    //     size : [257,350],
    //     id: "vaseSuspendu",
    //     name: "Vase suspendu",
    //     text: "Dans ce vase, les fleurs sont placées individuellement, avec attention et conscience du geste, dans les trous du plateau prévus à cet effet. Un autre regard peut alors se poser sur la fleur, à la fois comme objet unique de contemplation ou comme partie intégrante d’une composition.<br><br>Réalisé avec Sidonie Couëdel.",
    //     desc:"",
    //     type: "Projet d'études",
    //     date: "2017",
    //     spot : 1,
    //     imgSrc1 : "vase-suspendu-triptique.gif",
    //     scale : 0.6,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // MEUBLE A BAZAR
    // {
    //     offset : [757,0],
    //     size : [420,395],
    //     id: "meubleBazar",
    //     name: "Meuble à bazar",
    //     text: "J'ai fabriqué ce meuble pour ranger efficacement et de manière économe en place mes dessins et les objets que je collecte pour bricoler. Je l'ai essentiellement conçu à partir de matière récupérée, dont je disposais à proximité.",
    //     desc:"",
    //     type: "Projet personnel",
    //     date: "2023",
    //     spot : 1,
    //     imgSrc1 : "meuble-a-bazar.jpg",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet",
    //     link : "oui/",
    //     mirror : 1,
    //     miniature : 1,
        
    // },
    // PARLERS ESPACE
    {
        offset : [900,500],
        size : [837,532],
        id: "parlersEspace",
        name: "Parlers Espace",
        text: "Dans le monde matériel auquel nous appartenons, notre personnalité transparaît à travers nos espaces. Des langages, propres à chacun émergent des aménagements, des objets avec lesquels nous bâtissons nos quotidiens.<br> <br> Dans ce mémoire, je pars à l'exploration de ces 'parlers espace' qui me fascinent. (attention ! ne fonctionne pas sur Safari)",
        desc:"",
        type: "Mémoire",
        date: "2021",
        spot : 1,
        imgSrc1 : "parlersespace.gif",
        scale : 1,
        imgSrc2 : "none",
        class : "multimedia mediation illustration ",
        link : "https://bigcawo.itch.io/parlers-espaces",
        mirror : 0,
        miniature : 0,
        
    },
    // POMME DE TERRE
    {
        offset : [4100,0],
        size : [653,586],
        id: "pommeDeTerre",
        name: "Pomme de Terre",
        text: "Une pomme de terre nostalgique du passé se réveille dans une caisse. Elle espère être cuisinée comme ses aïeules, mais le monde de la cuisine a bien changé...<br><br>Réalisé avec Théophile Perrot.",
        desc:"",
        type: "Projet d'études",
        date: "2019",
        spot : 1,
        imgSrc1 : "pommedeterre.jpg",
        scale : 1,
        imgSrc2 : "none",
        class : "multimedia mediation ",
        link : "",
        mirror : 0,
        miniature : 0,
        
    },
    // CARNETS
    // {
    //     offset : [3503,300],
    //     size : [238,335],
    //     id: "carnets",
    //     name: "Carnets",
    //     text: "Mes carnets m'accompagnent partout où je vais. En voyage, dans la rue, dans le métro, chez moi, chez mes amis...<br><br>J'y dessine et j'y écrit ce que je vois, pense et imagine, sans but particulier. Ils évoluent avec moi.",
    //     desc:"",
    //     type: "",
    //     date: "",
    //     spot : 1,
    //     imgSrc1 : "carnets.png",
    //     scale : 0.6,
    //     imgSrc2 : "none",
    //     class : "illustration ",
    //     link : "",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // POLES IMAGES
    {
        offset : [1600,-3],
        size : [445,589],
        id: "poleImage",
        name: "Qu'est ce qu'un Pôle Image ?",
        text: "Cette pastille mixant plusieurs types d'animation est une réponse de l'entreprise Cinémagraphic à un appel à projet lancé par les Pôles Images.<br><br>J'y ai été assistant à la réalisation, à l'animation et à la prise de vue.",
        desc:"",
        type: "Projet professionnel",
        date: "2024",
        spot : 1,
        imgSrc1 : "poleimage.png",
        scale : 1,
        imgSrc2 : "none",
        class : "multimedia mediation ",
        link : "",
        mirror : 0,
        miniature : 0,
        
    },
    // ILLUSTRATIONS
    {
        offset : [2900,500],
        size : [650,350],
        id: "illustrations",
        name: "Illustrations",
        text: "",
        desc:"",
        type: "",
        date: "",
        spot : 1,
        imgSrc1 : "none",
        scale : 1,
        imgSrc2 : "none",
        class : "illustration ",
        link : "",
        mirror : 0,
        miniature : 0,
        
    },
    // MOBILIER GRILLAGE
    // {
    //     offset : [0,-10],
    //     size : [597,386],
    //     id: "mobilierGrillage",
    //     name: "Mobilier Grillage",
    //     text: "Quoi de plus pérenne que de fabriquer les objets qui nous entourent en utilisant des matières réemployées ?<br><br>C’est dans cette optique que j’ai imaginé ce mobilier de jardin, fabriqué à partir d’un gisement de matière récupérée, le panneau grillagé rigide.",
    //     desc:"",
    //     type: "Projet personnel",
    //     date: "depuis 2020",
    //     spot : 1,
    //     imgSrc1 : "mobiliergrillage.jpg",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "",
    //     mirror : 0,
    //     miniature : 1,
        
    // },

    // CHARLETTE
    // {
    //     offset : [5402,0],
    //     size : [761,589],
    //     id: "charlette",
    //     name: "Charlette",
    //     text: "Cette remorque permet de transporter facilement une palette aux normes européennes avec n'importe quel vélo.<br><br> Ce projet est à l'initiative de l'association Veloma, que j'ai eu le plaisir d'assister dans la conception et la réalisation de ce premier prototype.",
    //     desc:"",
    //     type: "Projet professionnel",
    //     date: "2023",
    //     spot : 1,
    //     imgSrc1 : "none",
    //     scale : 1,
    //     imgSrc2 : "none",
    //     class : "objet ",
    //     link : "https://veloma.org/2024/02/16/charlette-charrette-palette/",
    //     mirror : 0,
    //     miniature : 0,
        
    // },
    // STELLARIUM
    {
        offset : [5100,0],
        size : [882,598],
        id: "stellarium",
        name: "Stellarium",
        text: "Cet observatoire stellaire est un de mes premiers projets.<br><br> J'y propose au spectateur une visite guidée de la voie lactée et des exoplanètes potentiellement habitables proches de la terre.",
        desc:"",
        type: "Projet personnel",
        date: "2016",
        spot : 1,
        imgSrc1 : "stellarium.png",
        scale : 1,
        imgSrc2 : "none",
        class : "objet mediation",
        link : "",
        mirror : 0,
        miniature : 0,
        
    },
    // ANIMATIONS
    {
        offset : [3800,660],
        size : [491,350],
        id: "animations",
        name: "Animations",
        text: "Vous trouverez par ici une selection d'animations que j'ai créées dans le cadre de projets ou pour le simple plaisir de donner vie aux images !",
        desc:"",
        type: "",
        date: "",
        spot : 1,
        imgSrc1 : "animation_accueil.gif",
        scale : 0.6,
        imgSrc2 : "none",
        class : "illustration multimedia",
        link : "",
        mirror : 0,
        miniature : 0,
        
    },


    // // SITE WEB
    {
        offset : [2100,640],
        size : [625,756],
        id: "siteWeb",
        name: "Site Web",
        text: "Le site sur lequel vous vous trouvez est un projet personnel que j'alimente et approfondis depuis plus d'un an. Je l'ai pensé comme un lieu virtuel, zone de stockage pour mes différents travaux et vitrine pour ma pratique d'artiste designer. Il reflète ma personnalité et mon amour pour les espace à explorer. <!--On peut y retrouver, disposés au sein d'un espace dessiné et bidimensionnel, mes différents travaux ainsi que des informations sur ma pratique et les services que je propose. .J'ai programmé ce site intégralement en HTML, CSS et JavaScript. Il est à la fois pour moi un prétexte pour apprendre la programmation, une vitrine et un objet qui me permet de mieux cerner qui je suis et ce vers quoi j'oriente ma vie professionnelle-->",
        desc:"",
        type: "Projet personnel",
        date: "depuis 2023",
        spot : 1,
        imgSrc1 : "none",
        imgSrc2 : "none",
        class : "objet ",
        link : "",
        mirror : 0,
        miniature : 0,

    },
    // MADMAXVR
    {
        offset : [4800,550],
        size : [335,335],
        id: "madMaxVr",
        name: "Max Max VR",
        text: "Dans le cadre d'un projet à l'ENSCI, Joseph Henry et moi avons travaillé à la reproduction d'une scène de course poursuite du film 'Mad Max Fury Road' en réalité virtuelle",
        desc:"",
        type: "Projet d'études",
        date: "2020",
        spot : 1,
        imgSrc1 : "madmax-steeringwheel.jpg",
        imgSrc2 : "none",
        class : "objet ",
        link : "https://johhnry.com/work/mad-max-vr.html",
        mirror : 1,
        miniature : 0,

    },


];






